server {
    #listen [::]:80;
    #ips de acceso del servidor, incluidos certificados ssl y dominios.
    #server_name 54.90.253.94 localhost 0.0.0.0 127.0.0.1;
    server_name 100.48.11.7 sofia.willay.ai localhost 0.0.0.0 127.0.0.1;
    #server_name 0.0.0.0;

    access_log /var/log/nginx/nginx-access.log;

    error_log /var/log/nginx/nginx-error.log;

    proxy_connect_timeout 120s;
    proxy_read_timeout 300s;


    location /static/ {
        #complete route project
        root /home/ubuntu/SOFIA/Sofia;
    }

   location / {
        include proxy_params;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
   location /prometheus/ {
        proxy_pass http://localhost:9090/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
	
	allow 100.48.11.7;
    
        #auth_basic "Acceso restringido";
        #auth_basic_user_file /etc/nginx/.htpasswd;
    }	



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/sofia.willay.ai/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/sofia.willay.ai/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    # Nginx Status
    location /nginx_status {
        stub_status on;
        access_log on;
        allow 127.0.0.1;
	allow 100.48.11.7;
        #deny all;
    }

    # --- Barberia System ---
    location /barberia/ {
        proxy_pass http://localhost:8002/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
server {
    if ($host = sofia.willay.ai) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name 100.48.11.7 sofia.willay.ai localhost 0.0.0.0 127.0.0.1;

    # --- Barberia System ---
    location /barberia/ {
        proxy_pass http://localhost:8002/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        return 404; # managed by Certbot
    }
}
