"""add_service_type_model

Revision ID: 19d1838ae20c
Revises: 732b882b6722
Create Date: 2026-06-01 20:28:02.302309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d1838ae20c'
down_revision: Union[str, None] = '732b882b6722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_types_company_id'), 'service_types', ['company_id'], unique=False)
    op.create_index(op.f('ix_service_types_id'), 'service_types', ['id'], unique=False)
    op.create_table('barber_service_types',
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.PrimaryKeyConstraint('barber_id', 'service_type_id')
    )
    op.add_column('service_catalog', sa.Column('service_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_service_catalog_service_type_id'), 'service_catalog', ['service_type_id'], unique=False)
    op.create_foreign_key('fk_service_catalog_service_type_id', 'service_catalog', 'service_types', ['service_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_service_catalog_service_type_id', 'service_catalog', type_='foreignkey')
    op.drop_index(op.f('ix_service_catalog_service_type_id'), table_name='service_catalog')
    op.drop_column('service_catalog', 'service_type_id')
    op.drop_table('barber_service_types')
    op.drop_index(op.f('ix_service_types_id'), table_name='service_types')
    op.drop_index(op.f('ix_service_types_company_id'), table_name='service_types')
    op.drop_table('service_types')
    # ### end Alembic commands ###
