"""add photo_url barber logo_url company

Revision ID: 7293ecfa396f
Revises: f1a2b3c4d5e6
Create Date: 2026-05-19 10:45:11.214524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7293ecfa396f'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barbers', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'logo_url')
    op.drop_column('barbers', 'photo_url')
    # ### end Alembic commands ###
