"""add barber hours model

Revision ID: 732b882b6722
Revises: 7293ecfa396f
Create Date: 2026-05-29 21:25:21.035105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732b882b6722'
down_revision: Union[str, None] = '7293ecfa396f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barber_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('day_of_week', sa.String(length=50), nullable=True),
    sa.Column('exceptions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barber_hours_barber_id'), 'barber_hours', ['barber_id'], unique=False)
    op.create_index(op.f('ix_barber_hours_company_id'), 'barber_hours', ['company_id'], unique=False)
    op.create_index(op.f('ix_barber_hours_id'), 'barber_hours', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barber_hours_id'), table_name='barber_hours')
    op.drop_index(op.f('ix_barber_hours_company_id'), table_name='barber_hours')
    op.drop_index(op.f('ix_barber_hours_barber_id'), table_name='barber_hours')
    op.drop_table('barber_hours')
    # ### end Alembic commands ###
