"""add_cash_register_closings

Revision ID: 766c1e26591f
Revises: d5e6f7a8b9c0
Create Date: 2026-05-15 17:50:15.210001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766c1e26591f'
down_revision: Union[str, None] = 'd5e6f7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_register_closings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('period_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sales_cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('product_sales_cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expenses_cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expected_cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discrepancy', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_register_closings_closed_at'), 'cash_register_closings', ['closed_at'], unique=False)
    op.create_index(op.f('ix_cash_register_closings_company_id'), 'cash_register_closings', ['company_id'], unique=False)
    op.create_index(op.f('ix_cash_register_closings_id'), 'cash_register_closings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_register_closings_id'), table_name='cash_register_closings')
    op.drop_index(op.f('ix_cash_register_closings_company_id'), table_name='cash_register_closings')
    op.drop_index(op.f('ix_cash_register_closings_closed_at'), table_name='cash_register_closings')
    op.drop_table('cash_register_closings')
    # ### end Alembic commands ###
