"""add_appointments_table

Revision ID: 779844f2924e
Revises: 766c1e26591f
Create Date: 2026-05-18 06:56:03.862547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779844f2924e'
down_revision: Union[str, None] = '766c1e26591f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_barber_id'), 'appointments', ['barber_id'], unique=False)
    op.create_index(op.f('ix_appointments_company_id'), 'appointments', ['company_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_at'), 'appointments', ['scheduled_at'], unique=False)
    op.create_foreign_key(None, 'barbers', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'clients', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'income_split_config', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'inventory_items', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'operating_manual_entries', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'payment_method_config', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'product_catalog', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'product_sales', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'sales', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'sales', 'inventory_items', ['courtesy_drink_item_id'], ['id'])
    op.create_foreign_key(None, 'service_catalog', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'service_catalog', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'product_sales', type_='foreignkey')
    op.drop_constraint(None, 'product_catalog', type_='foreignkey')
    op.drop_constraint(None, 'payment_method_config', type_='foreignkey')
    op.drop_constraint(None, 'operating_manual_entries', type_='foreignkey')
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.drop_constraint(None, 'income_split_config', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'barbers', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_scheduled_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_company_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_barber_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
